### ISSUE TITLE
Document algorithm 

### ISSUE THREAD

**Issue by bjartek** [onflow/atree#211]
Can you docment why this scales?

Given its name i kind of assume it is using https://en.m.wikipedia.org/wiki/A*_search_algorithm or a similar algorithm but this should be stated.

Also a rough idea on tradeoffs. Nothing is fast for everything. O notation would be helpfull.

**Comment by turbolent** [comment]
There might be some documentation on the implementation detail in the future, but that's not a priority at the moment.

The data structures in atree are related to [B+ trees](https://en.wikipedia.org/wiki/B%2B_tree): Trees store metadata in internal nodes, and actual data in leaf nodes. All nodes are stored in fixed size "slabs", which are usually called "blocks" or "pages" in other systems, small blocks of storage (mapped to registers in the state trie). The trees automatically merge/split  nodes to keep the data in the slabs compact and reduce the number of slabs.

**Comment by bluesign** [comment]
Yeah on an alternate reality: 

- First it would be a FLIP
- Then there would be some discussion about the issue 
- Then one implementation decided and implemented 

This is core of the blockchain, it is not some implementation detail of which sort function cadence is using.

For me super disappointing this development is going like this.
